### ISSUE TITLE
'LoginRequiredMiddleware' object is not callable

### ISSUE THREAD

**Issue by whaleforever** [mgrouchy/django-stronghold#57]
I keep getting error TypeError: 'LoginRequiredMiddleware' object is not callable.
I'm using django 1.10 and using master branch. 

any reason why this is happening?
thanks

**Comment by SunilMohanAdapa** [comment]
If you are using new style middleware classes using `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES` setting, then you will see this issue.  This is because django stronghold does not yet support the new style middleware. See #53.

As a word around you should be able to do something like this (rough code, untested):
```python
from django.utils.deprecation import MiddlewareMixin
from stronghold import LoginRequiredMiddleware

class MyLoginRequiredMiddleware(MiddlewareMixin, LoginRequiredMiddleware):
    pass
```
Then use this class instead of `strong.LoginRequiredMiddleware` in your `MIDDLEWARE` list in Django settings.

**Comment by whaleforever** [comment]
somehow I can get it working, maybe you should update the docs though, for django 1.10.

overall (there is wrong import, it should be from .middleware )

```
from django.utils.deprecation import MiddlewareMixin
from stronghold.middleware import LoginRequiredMiddleware


class LoginRequiredStrongholdMiddleware(MiddlewareMixin, LoginRequiredMiddleware):
    pass
```

**Comment by mammique** [comment]
Here is a patch: https://github.com/mammique/django-stronghold/commit/cddf4a0c64b82b33a9530076cdd71d79ee27c8e1

**Comment by amard33p** [comment]
Please accept this patch.
